#Copyright @ISmartCoder
#Updates Channel @abirxdhackz 
API_ID = YOUR_API_ID
API_HASH = "YOUR_API_HASH"
BOT_TOKEN = "YOUR_BOT_TOKEN"
TELE_ID = YOUR_API_ID
TELE_HASH = "YOUR_API_HASH"
IMGAI_API_KEY = "YOUR_IMAGE_API_KEY"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
REPLICATE_API_TOKEN = "YOUR_REPLICATE_API_TOKEN"
GEMINI_API_KEY = "YOUR_GMINI_API_KEY"
GROQ_API_KEY = "YOUR_GROK_API_KEY"
SPOTIFY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"
BASE_URL = "This A360 API Base Url"
MONGO_URL = "Your MongoDB Url"